# Generated by Django 4.0.3 on 2022-04-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registeration_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('time_of_lecture', models.DateTimeField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.lecturer')),
                ('student', models.ManyToManyField(to='attendance.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.unit')),
            ],
        ),
    ]
